#!/bin/bash

python3 ./userbot/main.py --reset_control_group